name: labAvanzado
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.11
  # Librerías científicas
  - numpy
  - matplotlib
  - scipy
  - plotly
  # Compilador Fortran
  - m2w64-gcc-fortran        # gfortran para Windows (vía conda-forge)
  # Utilidades
  - pip
  - pip:
    - plotly                  # por si conda-forge no tiene la versión más reciente